task:
  name: Build LineageOS for Samsung A34x
  container:
    image: cirrusci/android-sdk:29
    cpu: 4
    memory: 16G
  env:
    AOSP_BRANCH: lineage-21.0
    DEVICE_CODENAME: a34x-ap2a

  script:
    # Update package list dan install dependencies
    - apt-get update
    - apt-get install -y openjdk-11-jdk git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig rsync ccache lz4 make

    # Install repo tool
    - curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
    - chmod a+x /usr/local/bin/repo

    # Konfigurasi git
    - git config --global user.name "xnnnsets"
    - git config --global user.email "solihinprampampam@gmail.com"

    # Sinkronisasi kode sumber LineageOS
    - repo init -u https://github.com/LineageOS/android.git -b $AOSP_BRANCH
    - repo sync --force-sync

    # Clone device tree, vendor, hardware, dan sepolicy
    - git clone https://github.com/Moonlight7728/device_samsung_a34x_aosp ./device/samsung/a34x
    - git clone https://github.com/Moonlight7728/android_vendor_samsung_a34x ./vendor/samsung/a34x
    - git clone https://github.com/xiaomi-mediatek-devs/android_hardware_mediatek ./hardware/mediatek
    - git clone https://github.com/xiaomi-mediatek-devs/android_device_mediatek_sepolicy_vndr ./device/mediatek/sepolicy_vndr

    # Setup build environment dan build ROM
    - source build/envsetup.sh
    - lunch lineage_$DEVICE_CODENAME-eng
    - mka bacon

  artifacts:
    paths:
      - out/target/product/$DEVICE_CODENAME/*.zip  # Hasil build ROM (.zip)
