task:
  name: Build LineageOS for Samsung A34x
  container:
    image: xnnnsets/android-lineageos-build  # Ganti dengan username yang kamu buat
    cpu: 4
    memory: 16G  # Sesuaikan dengan batas maksimum

  env:
    AOSP_BRANCH: lineage-21.0
    DEVICE_CODENAME: a34x-ap2a

  script:
    # Konfigurasi git
    - git config --global user.name "xnnnsets"
    - git config --global user.email "solihinprampampam@gmail.com"

    # Sinkronisasi kode sumber LineageOS
    - repo init -u https://github.com/LineageOS/android.git -b $AOSP_BRANCH
    - repo sync --force-sync

    # Clone device tree, vendor, hardware, dan sepolicy
    - git clone https://github.com/Moonlight7728/device_samsung_a34x_aosp ./device/samsung/a34x
    - git clone https://github.com/Moonlight7728/android_vendor_samsung_a34x ./vendor/samsung/a34x
    - git clone https://github.com/xiaomi-mediatek-devs/android_hardware_mediatek ./hardware/mediatek
    - git clone https://github.com/xiaomi-mediatek-devs/android_device_mediatek_sepolicy_vndr ./device/mediatek/sepolicy_vndr

    # Setup build environment dan build ROM
    - source build/envsetup.sh
    - lunch lineage_$DEVICE_CODENAME-eng
    - mka bacon

  artifacts:
    paths:
      - out/target/product/$DEVICE_CODENAME/*.zip  # Hasil build ROM (.zip)
