task:
  name: Build LineageOS for Samsung A34x
  container:
    image: cirrusci/android-sdk:29
    cpu: 4
    memory: 24G
  env:
    AOSP_BRANCH: lineage-20.0
    DEVICE_CODENAME: a34x-ap2a

  script:
    - git config --global user.name "Your Name"
    - git config --global user.email "your_email@example.com"
    - repo init -u https://github.com/LineageOS/android.git -b $AOSP_BRANCH
    - repo sync --force-sync
    - git clone https://github.com/Moonlight7728/device_samsung_a34x_aosp ./device/samsung/a34x
    - git clone https://github.com/Moonlight7728/android_vendor_samsung_a34x ./vendor/samsung/a34x
    - git clone https://github.com/xiaomi-mediatek-devs/android_hardware_mediatek ./hardware/mediatek
    - git clone https://github.com/xiaomi-mediatek-devs/android_device_mediatek_sepolicy_vndr ./device/mediatek/sepolicy_vndr
    - source build/envsetup.sh
    - lunch lineage_$DEVICE_CODENAME-eng
    - mka bacon

  artifacts:
    paths:
      - out/target/product/$DEVICE_CODENAME/*.zip
